linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

run:
  timeout: 5m

issues:
  exclude-generated: true
  exclude-rules:
    - path: "zz_generated.*"
      linters:
        - govet
        - errcheck
        - staticcheck
        - unused
        - gosimple
        - ineffassign
        - typecheck
