package docs

import (
	"fmt"
	"strings"
)

type DocGenerator struct {
	projectName string
	artifacts   []ArtifactRef
}

type ArtifactRef struct {
	Path    string
	Size    int
	Type    string
}

func NewGenerator(projectName string, artifacts []ArtifactRef) *DocGenerator {
	return &DocGenerator{
		projectName: projectName,
		artifacts:   artifacts,
	}
}

type ArchitectureDiagram struct {
	Nodes   []DiagramNode
	Edges   []DiagramEdge
}

type DiagramNode struct {
	ID   string
	Name string
	Type string
}

type DiagramEdge struct {
	From string
	To   string
	Kind string
}

func (g *DocGenerator) GenerateAPIDocs(endpoints []Endpoint) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# %s API Documentation\n\n", g.projectName))
	sb.WriteString("## Endpoints\n\n")
	sb.WriteString("| Method | Path | Description |\n")
	sb.WriteString("|--------|------|-------------|\n")
	for _, ep := range endpoints {
		sb.WriteString(fmt.Sprintf("| %s | %s | %s |\n", ep.Method, ep.Path, ep.Description))
	}
	return sb.String()
}

type Endpoint struct {
	Method      string
	Path        string
	Description string
}

func (g *DocGenerator) GenerateArchitectureDiagram(services, modules []string) string {
	var sb strings.Builder
	sb.WriteString("```mermaid\ngraph TD\n")
	sb.WriteString(fmt.Sprintf("    P[%s] --> M1\n", g.projectName))
	for i, mod := range modules {
		nodeID := fmt.Sprintf("M%d", i+1)
		sb.WriteString(fmt.Sprintf("    %s[%s]\n", nodeID, mod))
		if i > 0 {
			prevID := fmt.Sprintf("M%d", i)
			sb.WriteString(fmt.Sprintf("    %s --> %s\n", prevID, nodeID))
		}
	}
	for i, svc := range services {
		nodeID := fmt.Sprintf("S%d", i+1)
		sb.WriteString(fmt.Sprintf("    %s{%s}\n", nodeID, svc))
		if len(modules) > 0 {
			lastMod := fmt.Sprintf("M%d", len(modules))
			sb.WriteString(fmt.Sprintf("    %s --> %s\n", lastMod, nodeID))
		}
	}
	sb.WriteString("```\n")
	return sb.String()
}

func (g *DocGenerator) GenerateProjectDocs() string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# %s\n\n", g.projectName))
	sb.WriteString("Generated by NAEOS documentation generator.\n\n")
	sb.WriteString("## Project Structure\n\n")
	for _, a := range g.artifacts {
		sb.WriteString(fmt.Sprintf("- `%s` (%s, %d bytes)\n", a.Path, a.Type, a.Size))
	}
	sb.WriteString("\n## Quick Start\n\n")
	sb.WriteString("1. Review the specification file\n")
	sb.WriteString("2. Install dependencies\n")
	sb.WriteString("3. Run the application\n")
	return sb.String()
}
